"""empty message

Revision ID: 9b2e842fdb78
Revises:
Create Date: 2025-07-08 21:43:26.485365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b2e842fdb78"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaints",
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "closed", name="statusenum"),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "sentiment",
            sa.Enum(
                "positive",
                "negative",
                "neutral",
                "unknown",
                name="sentimentenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum("Техническая", "Оплата", "Другое", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaints")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("complaints")
    # ### end Alembic commands ###
